---

- name: General Config

  hosts: Cisco_Switches

  tasks:

  - name: Add Banner

    ios_banner:
      banner: login
      text: |
        Hiya Buddy!
      state: present

  - name: Add loopback

    ios_interface:
      name: Loopback1
      state: present 
